# Start from the official Node image
FROM node:22.14.0

# Install GitHub CLI and dependencies
RUN apt-get update && \
    apt-get install -y curl git && \
    apt-get update && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Docker CLI (needed for act to work with Docker-in-Docker)
RUN curl -fsSL https://get.docker.com | sh

# Install act
RUN curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | bash


# # Enable corepack and install pnpm
# RUN corepack enable && echo "Y" | corepack prepare pnpm@latest --activate

# # pnpm global
# RUN pnpm setup && source /root/.bashrc

# RUN pnpm install turbo --global

