name: Reusable Workflows

on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string

jobs:
  build:
    if: ${{ inputs.action == 'build' }}
    runs-on: ubuntu-latest
    steps:
    - name: Install pnpm
        uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Build
      run:  pnpm run build

  test:
    if: ${{ inputs.action == 'test' }}
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Running tests..."
